"""add column

Revision ID: 0f2ed2ff2263
Revises: 3142873aa6a8
Create Date: 2018-09-20 04:53:00.874146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2ed2ff2263'
down_revision = '3142873aa6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_content', sa.String(), nullable=True))
    op.drop_column('comments', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment_content')
    # ### end Alembic commands ###
