"""add column

Revision ID: 3142873aa6a8
Revises: 2103fd33d77e
Create Date: 2018-09-20 04:32:59.842359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3142873aa6a8'
down_revision = '2103fd33d77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('comments', 'comment_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'description')
    # ### end Alembic commands ###
